### ISSUE TITLE
Reducers shouldn't have side effects

### ISSUE THREAD

**Issue by gaearon** [bruz/react-native-redux-groceries#1]
In this example, the reducer calls a side effect to persist the data.
Instead, you should use `store.subscribe()` to react to store changes and persist it there.

**Comment by bruz** [comment]
Thanks for taking the time to review this, and catching that!

I've [moved the offline persistence out of the reducer](https://github.com/bruz/react-native-redux-groceries/commit/cec52b1b80a948cdb0732510615fa9ec03bb43fa) as you suggested.

**Comment by gaearon** [comment]
:+1:
