### ISSUE TITLE
Upgrading to Firebase v3.x

### ISSUE THREAD

**Issue by simonjblack** [bruz/react-native-redux-groceries#10]
Not an issue as such, but to note that it's very simple and easy to upgrade this to Firebase 3, which supports React Native from 3.1+. Update to new version of firebase in npm and then in Groceries.js the following replace the Firebase references above the component:

```
import * as firebase from 'firebase'
...
const firebaseConfig = {
    apiKey: “YOURKEY”,
    authDomain: “YOURDOMAIN”,
    databaseURL: “YOURDATABASEURL”,
    storageBucket: "",
  };
const firebaseApp = firebase.initializeApp(firebaseConfig);
const itemsRef = firebaseApp.database().ref()
const connectedRef = firebaseApp.database().ref('.info/connected')
```

**Comment by bruz** [comment]
Thanks for the heads-up about the new Firebase version bringing back React Native support, and the upgrade notes. I've updated the app to use the new Firebase and all seems well on both iOS and Android.
