### ISSUE TITLE
Error when updating to React Native 0.30.0

### ISSUE THREAD

**Issue by bruz** [bruz/react-native-redux-groceries#11]
iOS works fine, but on Android updating to React Native 0.30.0 causes the following error when clearing an item from the list: `Error while updating property 'transform' of a view managed by: RCTView`.

**Comment by MrRoyce** [comment]
There are other projects complaining about a similar issue:

https://github.com/react-native-community/react-native-linear-gradient/issues/84
https://github.com/oblador/react-native-vector-icons/issues/134

I'm on react-native 0.31 and it still occurs.  Any ideas on a fix?

**Comment by bruz** [comment]
Thanks for those links. I'd seen one of those when investigating this, but not the other. I haven't had time to look into this very deeply and don't have any good leads on what's going on right now, but hope to spend some time on it soon.

I also tried bumping up to 0.31.0 in case it helped, but also see the same error there.

**Comment by bruz** [comment]
OK, after looking further into this, I discovered that the [`measure` call on the list item](https://github.com/bruz/react-native-redux-groceries/blob/140bdc4e2dc9c5f134c5f383e373b996d9bf16e1/src/components/Item.js#L31) was returning `undefined` in its callback. So the error updating the `transform` property makes sense, given `undefined` was being fed into it.

It appears to be the same issue seen at https://github.com/facebook/react-native/issues/3282, so setting `collapsable` to `false` fixed it.
