### ISSUE TITLE
Error running with Xcode with release On

### ISSUE THREAD

**Issue by ghost** [bruz/react-native-redux-groceries#12]
No problem running with xcode on debug mode but with release mode, I get the following error:

Undefined symbols for architecture arm64:
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "operator new[](unsigned long)", referenced from:
      ___39-[RCTJSCExecutor registerNativeRequire]_block_invoke in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor loadRAMBundle:error:] in libReact.a(RCTJSCExecutor.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "operator delete[](void*)", referenced from:
      -[RCTJSCExecutor dealloc] in libReact.a(RCTJSCExecutor.o)
      ___39-[RCTJSCExecutor registerNativeRequire]_block_invoke in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor loadRAMBundle:error:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor .cxx_destruct] in libReact.a(RCTJSCExecutor.o)
  "___gxx_personality_v0", referenced from:
      -[RCTJavaScriptContext initWithJSContext:onThread:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext invalidate] in libReact.a(RCTJSCExecutor.o)
      RCTNSErrorFromJSError(RCTJSCWrapper_, OpaqueJSContext const_, OpaqueJSValue const*) in libReact.a(RCTJSCExecutor.o)
      +[RCTJSCExecutor runRunLoopThread] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor initWithUseCustomJSCLibrary:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor context] in libReact.a(RCTJSCExecutor.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bruz** [comment]
Thanks for spotting that! There was a linker flag `-lc++` that I'd added locally but hadn't checked in since I missed seeing it among the other local changes to my `project.pbxproj` that I didn't want to go in. I've pushed that change, can you see if it fixes the problem?

**Comment by bruz** [comment]
Closing this since I believe https://github.com/bruz/react-native-redux-groceries/commit/652414903950802924976bc4c732f6da34f91ea4 fixes it, but feel free to re-open if that fix didn't work for you.
