### ISSUE TITLE
Firebase configuratuon?

### ISSUE THREAD

**Issue by itagakixt** [bruz/react-native-redux-groceries#16]
Hello react-native-redux-groceries,

 In the Firebase Console under the Database section, I did Rules tab, changed as readme told.
But offline is displayed at groceries starting, 

render() {
    console.log('PROPS!')
    console.log(this.props)
    let items, readonlyMessage
    if (this.props.connected) {
      items = this.props.onlineItems
    } else if (this.props.connectionChecked) {
      items = this.props.offlineItems
      readonlyMessage = <Text style={styles.offline}>XXXXXX Offline</Text> <--- This 

Why this occurred?

and add operation is rejected with following message.

Possible unhandled promise Rejection (id:0):
PERMMISION_DENIED:Permission deined

FIREBASE WARNING: set/at/ items/1x1n failed.
Permission denied

Some setting will be needed to fix this. Where is the check point?

Thanks
Shoji Itagaki

**Comment by bruz** [comment]
I'm not sure what's going on here. I just created a brand new Firebase project, and if I try running the app _without_ changing the rules I see the error messages you mention, but then when I update the rules with the ones from the README it works fine.

I don't have any great suggestions, other than double-checking your credentials in the `config.js` and double-checking that the rules saved properly in Firebase.

**Comment by itagakixt** [comment]
Thanks!

I will check it again.

**Comment by itagakixt** [comment]
Hello bruz,

config.js becomes OK after check.

react-native-redux-groceries works fine!!!

Thanks
Shoji

**Comment by bruz** [comment]
Great!
