### ISSUE TITLE
Unable to resolve module react/lib/ReactUpdates

### ISSUE THREAD

**Issue by sagivo** [bruz/react-native-redux-groceries#17]
ios run error: 
```
Unable to resolve module react/lib/ReactUpdates from /Users/xxxx/dev/side/react/react-native-redux-groceries/node_modules/react-native/Libraries/react-native/react-native.js: Module does not exist in the module map or in these directories:
  /Users/xxxx/dev/side/react/react-native-redux-groceries/node_modules/react-native/node_modules/react/lib
,  /Users/xxxx/dev/side/react/react-native-redux-groceries/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 1054
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2205
CFRunLoopRunSpecific + 420
GSEventRunModal + 161
UIApplicationMain + 159
main + 111
start + 1
```
<img width="360" alt="screen shot 2016-11-21 at 9 59 43 pm" src="https://cloud.githubusercontent.com/assets/1484886/20509320/d6804914-b035-11e6-8b00-df848c5f0aa9.png">

**Comment by bruz** [comment]
Thanks for the heads-up on this. I was able to reproduce the problem by doing a fresh install of the app, but haven't been able to track down what's happening yet. Reverting the upgrade to the most recent React Native didn't help either, and I've tested the app every time I've upgraded React Native, so I suspect it's something outside of the codebase that's changed.

**Comment by sagivo** [comment]
@bruz in case it helps - installing a clean latest react-native project using `react-native init` and just coping your custom code works.

**Comment by bruz** [comment]
@sagivo great tip on how dropping the code into a freshly-generated React Native app got it working. I didn't take the time to isolate exactly what the problem was, but went ahead and updated all the files generated by doing a fresh `react-native init`. It looks like there were some inconsistencies that had crept in over the course of many incremental React Native upgrades, so I figured it would be good to bring the app up to parity anyway.

**Comment by sagivo** [comment]
@bruz thanks
