### ISSUE TITLE
0 bytes PNG file makes android build error while running "react-native run-android"

### ISSUE THREAD

**Issue by deathemperor** [bruz/react-native-redux-groceries#20]
Just wanna post it here so anyone who gets the same error knows what to do.

Errors:

`react-native run-android
Scanning 483 folders for symlinks in /usr/local/groceries/node_modules (6ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportRecyclerviewV72340Library
:app:prepareComAndroidSupportSupportV42340Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee101Library
:app:prepareComFacebookFrescoFbcore101Library
:app:prepareComFacebookFrescoFresco101Library
:app:prepareComFacebookFrescoImagepipeline101Library
:app:prepareComFacebookFrescoImagepipelineBase101Library
:app:prepareComFacebookFrescoImagepipelineOkhttp3101Library
:app:prepareComFacebookReactReactNative0433Library
:app:prepareComFacebookSoloaderSoloader010Library
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
AAPT err(Facade for 2040171574) : No Delegate set : lost message:libpng error: Read Error
Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

Reason: There's an 0 byte png file inside "android/app/src/main/res/mipmap-hdpi/".

How to solve: just remove the ic_launcher.png file

**Comment by bruz** [comment]
@deathemperor thanks so much for tracking that down! I didn't have a local android setup when I did the last React Native upgrade so hadn't tested on there.

I've pushed a fix (https://github.com/bruz/react-native-redux-groceries/commit/936418221c180ed7199381e0ce79fb92e4f6a3c7) so I'll go ahead and close this.
