### ISSUE TITLE
Doesnt Work?

### ISSUE THREAD

**Issue by ghost** [bruz/react-native-redux-groceries#5]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bruz** [comment]
Thanks for spotting that. It looks like I left the incorrect URL in the README instructions. It's updated to the correct one now.

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Plan to update to 0.16 for this demo any time soon?

**Comment by bruz** [comment]
I tried updating to 0.16 and ran into an issue that [appears to be from the move up to Babel 6](https://github.com/rackt/react-redux/issues/206). I was going to give this a little time to see if it gets resolved in redux/react-redux before digging into it some more.
