### ISSUE TITLE
Authentication example

### ISSUE THREAD

**Issue by tarkanlar** [bruz/react-native-redux-groceries#6]
Hey @bruz thanks for creating this example really helped a lot. Is it possible to make an example for authentication? I found this answer http://stackoverflow.com/a/31328688 but I am new with redux so couldn't handle that.

**Comment by bruz** [comment]
Authentication is such a common need that I can see how it'd be useful to include, but that implies having sign up in addition to sign in data that's scoped per user, and I'm just not sure I'll have the time to add that on in the near future. For your app maybe it'd be useful to look at another [example redux app doing authentication](https://github.com/bartonhammond/snowflake) and see if you could work from that?
