### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by reflog** [bruz/react-native-redux-groceries#8]
Hi!
Great example you have :+1: 
Any idea how to implement authentication?

**Comment by bruz** [comment]
I'm sure there are a great many ways to do this, but here's one take on it, using Firebase's email/password authentication:
- Create some new container components for top level views like sign up and sign in, and add React Native's [Navigator](https://facebook.github.io/react-native/docs/navigator.html) component to switch between the container components
- Add new `auth` async actions for sign in and sign up, which would use Firebase's `authWithPassword` and `createUser`, and dispatch actions based on starting and then success/failure (e.g. `AUTH`, `AUTH_SUCCESS` and `AUTH_FAILURE` for sign in).
- Add and `auth` reducer to set appropriate state for all the actions dispatched, for instance `isSigningIn` to show a progress indicator when rendering the login view.
- Have the container components do checks in `componentWillReceiveProps` for transitions between being authenticated and not and triggering the changes through the `Navigator` (which could be passed down as a prop to the container components) to switch to the appropriate container.

That's pretty rough and leaves a lot of details to the imagination, but is it helpful?

**Comment by reflog** [comment]
Thank @bruz !
Unfortunately (for me) - I was looking for doing the oAuth authentication and since it's based on window.open method - it won't work on native. Need to use custom G+/FB signin and pass the token to firebase.

Thanks again, though!
